name: benchmark

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Setup dependencies
        run: |
          pip install -r requirements.txt

      - name: Benchmark
        env:
          SUPABASE_DEV_URL: ${{ secrets.SUPABASE_DEV_URL }}
          SUPABASE_DEV_KEY: ${{ secrets.SUPABASE_DEV_KEY }}
          SUPABASE_DEV_USER: ${{ secrets.SUPABASE_DEV_USER }}
          SUPABASE_DEV_PASSWORD: ${{ secrets.SUPABASE_DEV_PASSWORD }}
          MODELZ_CLUSTER_ID: ${{ secrets.MODELZ_CLUSTER_ID }}
          MODELZ_BASIC_URL: ${{ secrets.MODELZ_BASIC_URL }}
          MODELZ_DISABLE_RICH: "true"
        run: |
          python main.py
          python main.py

      - name: Update to git
        env:
          GITHUB_TOKEN: ${{ secrets.PUSH_TOKEN }}
        run: |
          git config --global url."https://".insteadOf git://
          git config --global url."https://github.com/".insteadOf git@github.com:
          remote_repo="https://${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          remote_branch=main

          git config user.name "github-actions-bot"
          git config user.email "github-actions-bot@users.noreply.github.com"
          git add -f data/result.json README.md
          git commit -s -m "CI: update benchmark data and README"
          git push -f "${remote_repo}" main:${remote_branch}